### ISSUE TITLE
Problems fetching Jetson reference code

### ISSUE THREAD

**Issue by perkristian** [projectara/Android-wiki#1]
I am trying to fetch the Jetson reference code as described in https://github.com/projectara/Android-wiki/wiki/Build-and-Boot-Instructions-for-Jetson-reference-platform.
However, there seems to be some repositories that are not available so I cannot get the code.
Full log here: https://gist.github.com/perkristian/3d85f67d5146a569a080

Please advise.

**Comment by vishalbhoj** [comment]
The manifest has been fixed. Can you please do a repo sync and try to build the code.

**Comment by perkristian** [comment]
I am still having problems with the sync. I get a number of permission denied messages.

For instance:
Permission denied (publickey).
fatal: repository 'http://git-ara-mdk.linaro.org/platform/external/chromium_org/third_party/brotli/src/' not found

Full log:
https://gist.github.com/perkristian/03b018c3500f79dcf32c

**Comment by gkielian** [comment]
Hi, working through the wiki just now, I found a similar error with the `repo sync -j8` step:

``` sh
fatal: repository 'http://git-ara-mdk.linaro.org/platform/external/chromium_org/third_party/libaddressinput/src/' not found`
```

Full log:
https://gist.github.com/gkielian/aeec59e68ae458bb2e2e

**Comment by trsbalaji** [comment]
Hi , 

Anybody could be please help me..
I have download the project ara complete folder name [mydroid-ara] .  

user@User:~/mydroid-ara$ source build/envsetup.sh
including device/ara/pxa1928/vendorsetup.sh
including device/lge/hammerhead/vendorsetup.sh
including device/lge/mako/vendorsetup.sh
including device/nvidia/jetson/vendorsetup.sh
including device/generic/mini-emulator-mips/vendorsetup.sh
including device/generic/mini-emulator-arm64/vendorsetup.sh
including device/generic/mini-emulator-x86/vendorsetup.sh
including device/generic/mini-emulator-armv7-a-neon/vendorsetup.sh
including device/generic/mini-emulator-x86_64/vendorsetup.sh
including device/moto/shamu/vendorsetup.sh
including device/asus/grouper/vendorsetup.sh
including device/asus/tilapia/vendorsetup.sh
including device/asus/fugu/vendorsetup.sh
including device/asus/deb/vendorsetup.sh
including device/asus/flo/vendorsetup.sh
including device/samsung/manta/vendorsetup.sh
including device/htc/flounder/vendorsetup.sh
including sdk/bash_completion/adb.bash
user@User:~/mydroid-ara$ lunch jetson-eng|ara_pxa1928-eng
ara_pxa1928-eng: command not found

**Comment by gregkh** [comment]
Are you sure you have the needed packages installed in order to be able to build the android toolchain?  Please consult the android documentation for how to do that, if you can successfully build the Android public release, and you still have problems building this tree, please let us know in a new issue, not this one as it's different.

**Comment by trsbalaji** [comment]
Hi Greg Kroah-Hartman,

I have install all the packages in order but still am facing same issue. Could be please help me..

Thanks & Regards
Balaji Babu
